<script>
    require([
        'jquery'
    ], function($){

        var checklogin_button = $('#checklogin_button');

        checklogin_button.click(function () {
            $('#checklogin_message').html("");
            var params = {
                'form_key': checklogin_button.parents('form').find('input[name=form_key]').val(),
                'account_number': $("#chronorelais_shipping_account_number").val(),
                'account_pass': $("#chronorelais_shipping_account_pass").val()
            };
            $.ajax({
                url: "<?php echo $block->getAjaxUrl() ?>",
                method: "POST",
                data: params
            }).done(function( response ) {
                response = response.return;
                var msg = '<strong style="color:#007700;"><?php echo __("Identification réussie.") ?></strong>';
                if(typeof response.errorCode == "undefined") {
                    msg = '<strong><?php echo __("Le webservice est momentanément inaccessible. Veuillez réessayer plus tard.") ?></strong>';
                }
                else if(response.errorCode != 0)
                {
                    if(typeof response.message != "undefined") {
                        msg = '<strong style="color:#FF0000;">'+response.message+'</strong>';
                    } else {
                        msg = '<strong style="color:#FF0000;"><?php echo __("Les identifiants que vous avez renseignés ne sont pas valides.") ?></strong>'
                    }
                }
                $('#checklogin_message').html(msg);
            }).fail(function(){
                $('#checklogin_message').html("<?php echo __("Une erreur s'est produite.") ?>");
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<div id="checklogin_message"></div>