<?php $shippingMethod = $block->getData('shipping_method');
    $orderId = $block->getData('order_id');
    $weightOfOrder = $this->helper('Chronopost\Chronorelais\Helper\Data')->getWeightOfOrder($orderId);
?>

<div class="admin__page-section-item">
    <input type="hidden" value="<?= $shippingMethod; ?>" id="shipping_method_dimension">
    <div class="admin__page-section-item-title" style="margin-top: 10px">
        <span class="title"><?= __('Contract') . ' : '?></span>
        <?php echo $this->getContractsHtml($orderId);?>
    </div>
    <div class="admin__page-section-item-title" style="margin-top: 10px">
        <span class="title"><?= __('Nombre de colis :')?></span>
        <input value="1" id="nb_colis" data-orderid="<?php echo $orderId; ?>" data-inshipment=true  class="input-text admin__control-text" name="nb_colis" style="margin:0 5px 5px 5px;width: 4rem;"/>
    </div>
    <div class="admin__page-section-item-title">
        <span class="title"><?= __('Weight and dimensions :')?></span>
    </div>
    <div class="inputs-container">
        <div id="error-inputs">

        </div>
        <div>
            <table cellspacing="0" class="data" id="dimensions-weight" style="margin-top:8px">
                <colgroup><col width="20" class="a-center">
                    <col width="50">
                    <col width="50">
                    <col width="50">
                    <col width="50">
                </colgroup>
                <thead>
                <tr>
                    <th><span><?= __('Poids (KG)');?></span></th>
                    <th><span><?= __('Largeur');?></span></th>
                    <th><span><?= __('Hauteur');?></span></th>
                    <th><span><?= __('Longueur');?></span></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><input type="hidden" id="input_dimensions" name="dimensions" value="{}"></td>
                </tr>
                <tr class="dimensions-input-container">
                    <td class="weight_input">
                        <input value="<?= $weightOfOrder ? $weightOfOrder : 0 ?>" class="input-text admin__control-text" name='weight_input' data-inshipment="true" data-orderid="<?= $orderId; ?>" data-position="1" data-shipping-method="<?= $shippingMethod ?>" style="margin:0 5px 5px 5px;width:75px;"/>
                    </td>
                    <td class="width_input">
                        <input value="1" class="input-text admin__control-text" name='width_input' data-inshipment="true" data-orderid="<?= $orderId; ?>" data-position="1" data-shipping-method="<?= $shippingMethod ?>" style="margin:0 5px 5px 5px;width:75px;"/>
                    </td>
                    <td class="height_input">
                        <input value="1" class="input-text admin__control-text" name="height_input" data-inshipment="true" data-orderid="<?= $orderId; ?>" data-position="1" data-shipping-method="<?= $shippingMethod ?>" style="margin:0 5px 5px 5px;width:75px;"/>
                    </td>
                    <td class="length_input">
                        <input value="1" class="input-text admin__control-text" name="length_input" data-inshipment="true" data-orderid="<?= $orderId; ?>" data-position="1" data-shipping-method="<?= $shippingMethod ?>"style="margin:0 5px 5px 5px;width:75px;"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Chronopost_Chronorelais/js/shipmentDimensions":{
                "shippingmethod" = "<?= $shippingMethod ?>"
            }
        }
    }
</script>
